-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Orginization"
(
    orgid uuid NOT NULL,
    name text NOT NULL,
    domain character varying(255) NOT NULL,
    account uuid NOT NULL,
    "Type" text NOT NULL,
    PRIMARY KEY (orgid)
);

COMMENT ON TABLE public."Orginization"
    IS 'Represents a Salesforce Orginization.';

CREATE TABLE IF NOT EXISTS public."Account"
(
    "Name" character varying(255) NOT NULL,
    createddate date NOT NULL,
    active boolean,
    id uuid NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Account"
    IS 'An account that links orgs together.';

CREATE TABLE IF NOT EXISTS public."Org Connections"
(
    "user" uuid NOT NULL,
    org uuid NOT NULL,
    type text NOT NULL,
    access_token text,
    refresh_token text,
    id uuid,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Org Connections"
    IS 'Authentications to orgs.';

CREATE TABLE IF NOT EXISTS public."Users"
(
    name character varying(255) NOT NULL,
    id uuid NOT NULL GENERATED ALWAYS AS IDENTITY,
    email text,
    phone integer,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Users"
    IS 'Users';

ALTER TABLE IF EXISTS public."Orginization"
    ADD CONSTRAINT account FOREIGN KEY (account)
    REFERENCES public."Account" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Org Connections"
    ADD CONSTRAINT "Org " FOREIGN KEY (org)
    REFERENCES public."Orginization" (orgid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Org Connections"
    ADD CONSTRAINT "user" FOREIGN KEY ("user")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;